name: dart_project
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  mongo_dart: ^0.10.5
  objectid: ^4.0.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
